Yx feature fonts
redacademy/orcbc-winter-2020 pull request #15
Opened 2020-03-17 21:19 UTC by ybxiang05

added custom fonts to screens
removed comments as necessary

2020-03-17 23:12 UTC, siddharthparmar7 requested changes
Why are you adding pdf files to GitHub?

2020-03-17 23:12 UTC, siddharthparmar7 commented on client/package.json
> +    ]
No need to do this if you are using React Native >= 0.60

2020-03-18 16:30 UTC, iyuvraajsingh requested changes

2020-03-18 16:30 UTC, iyuvraajsingh commented on client/js/screens/Trips/Trips.js
>    console.log(props);
Please remove this console log.

2020-03-18 18:26 UTC, iyuvraajsingh approved these changes
Good Work!!

2020-03-18 18:27 UTC, merged